version: '3'
services:
  api:
    build: .
    command: uvicorn main:app --reload --port=8000 --host=0.0.0.0
    ports:
      - "8000:8000"
    volumes:
      - .:/app

  sql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: abcd

  phpmyadmin:
    image: phpmyadmin
    environment:
      PMA_ARBITRARY: 1
    ports:
      - "8080:80"
